name: build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      upload_artifact:
        description: 'Upload artifact to this run? [yes | no]'
        required: false
        default: 'no'

jobs:
  build:
    if: ${{ !contains(github.head_ref, 'translations/') }}
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_buildNumber: ${{ github.run_number }}
      ORG_GRADLE_PROJECT_runAttempt: ${{ github.run_attempt }}
      ORG_GRADLE_PROJECT_runningOnCi: ${{ true }}
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build with Gradle
      run: ./gradlew build
    - name: Read Project Version
      id: read_properties
      uses: christian-draeger/read-properties@1.1.1
      with:
        path: gradle.properties
        properties: version
    - name: Upload Artifact
      if: ${{ contains(github.event.inputs.upload_artifact, 'yes') }}
      env:
        project_version: ${{ steps.read_properties.outputs.value }}
      uses: actions/upload-artifact@v4
      with:
        name: build_artifacts
        path: build/libs/*
